In [1]:
from sqlalchemy import create_engine
import pandas as pd

In [3]:
# Membaca file CSV
df = pd.read_csv("data/employees.csv")

# Menampilkan 5 data pertama
display(df.head())

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,NaN
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services

In [ ]:
#mengecek karakteristik tabel
df.info()
print("Jumlah baris:", df.shape[0])
print("Jumlah kolom:", df.shape[1])
print(df.isnull().sum())
print(df.columns.tolist())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB
Jumlah baris: 1000
Jumlah kolom: 8
First Name            67
Gender               145
Start Date             0
Last Login Time        0
Salary                 0
Bonus %                0
Senior Management     67
Team                  43
dtype: int64
['First Name', 'Gender', 'Start Date', 'Last Login Time', 'Salary', 'Bonus %', 'Senior Management', 'Team']

In [ ]:
#merapihkan tabel seperti tulisan di kolom dikecilkan,spasi diganti dengan _ dll
df.columns = (
    df.columns.str.strip().str.lower().str.replace(" ", "_").str.replace("%", "percent")
)
print(df.columns.tolist())

['first_name', 'gender', 'start_date', 'last_login_time', 'salary', 'bonus_percent', 'senior_management', 'team']

In [ ]:
#mengubah menjadi datetime
df["start_date"] = pd.to_datetime(df["start_date"], errors="coerce")
df["start_year"] = df["start_date"].dt.year

In [ ]:
#handel missing value pada salary

df["salary"] = pd.to_numeric(df["salary"], errors="coerce")
print(df["salary"].isnull().sum())
df["salary"] = df["salary"].fillna(df["salary"].median())

0

In [ ]:
#handel missing value bonys

df["bonus_percent"] = pd.to_numeric(df["bonus_percent"], errors="coerce")
df["bonus_percent"] = df["bonus_percent"].fillna(0)

In [ ]:
#mengubah menjadi tulisan kapital di gender

df["gender"] = df["gender"].str.strip().str.upper()

In [ ]:
# mengubah menjadi bentuk boolean
df["senior_management"] = df["senior_management"].astype("boolean")

In [ ]:
#klasifikasi kelas sosial berdasarkan gaji

def kategori_gaji(salary):
    if salary < 50000:
        return "Rendah"
    elif salary < 100000:
        return "Menengah"
    else:
        return "Tinggi"
df["kategori_gaji"] = df["salary"].apply(kategori_gaji)

In [ ]:
#pengecekan hasil

display(df.head())
df.info()
print(df.isnull().sum())

,first_name,gender,start_date,last_login_time,salary,bonus_percent,senior_management,team,start_year,kategori_gaji
0,Douglas,MALE,1993-08-06,12:42 PM,97308,6.945,True,Marketing,1993,Menengah
1,Thomas,MALE,1996-03-31,6:53 AM,61933,4.170,True,NaN,1996,Menengah
2,Maria,FEMALE,1993-04-23,11:17 AM,130590,11.858,False,Finance,1993,Tinggi
3,Jerry,MALE,2005-03-04,1:00 PM,138705,9.340,True,Finance,2005,Tinggi
4,Larry,MALE,1998-01-24,4:47 PM,101004,1.389,True,Client Services,1998,Tinggi

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   first_name         933 non-null    object
 1   gender             855 non-null    object
 2   start_date         1000 non-null   datetime64[ns]
 3   last_login_time    1000 non-null   object
 4   salary             1000 non-null   int64
 5   bonus_percent      1000 non-null   float64
 6   senior_management  933 non-null    boolean
 7   team               957 non-null    object
 8   start_year         1000 non-null   int32
 9   kategori_gaji      1000 non-null   object
dtypes: boolean(1), datetime64[ns](1), float64(1), int32(1), int64(1), object(5)
memory usage: 68.5+ KB
first_name            67
gender               145
start_date             0
last_login_time        0
salary                 0
bonus_percent          0
senior_management     67
team                  43
start_year             0
kategori_gaji          0
dtype: int64

In [ ]:
#menyambungkan ke postgresql
engine = create_engine(
    "postgresql+psycopg2://etl_project:12345@localhost:5432/project-etl"
)

In [19]:
with engine.connect() as connection:
    print("Berhasil terhubung ke PostgreSQL!")

Berhasil terhubung ke PostgreSQL!

In [ ]:
#mengecek hasil akhir tabel di sql

df.to_sql("employees", engine, if_exists="replace", index=False)
query = """
SELECT *
FROM employees
LIMIT 10;
"""

df_check = pd.read_sql(query, engine)

display(df_check)

,first_name,gender,start_date,last_login_time,salary,bonus_percent,senior_management,team,start_year,kategori_gaji
0,Douglas,MALE,1993-08-06,12:42 PM,97308,6.945,True,Marketing,1993,Menengah
1,Thomas,MALE,1996-03-31,6:53 AM,61933,4.170,True,None,1996,Menengah
2,Maria,FEMALE,1993-04-23,11:17 AM,130590,11.858,False,Finance,1993,Tinggi
3,Jerry,MALE,2005-03-04,1:00 PM,138705,9.340,True,Finance,2005,Tinggi
4,Larry,MALE,1998-01-24,4:47 PM,101004,1.389,True,Client Services,1998,Tinggi
5,Dennis,MALE,1987-04-18,1:35 AM,115163,10.125,False,Legal,1987,Tinggi
6,Ruby,FEMALE,1987-08-17,4:20 PM,65476,10.012,True,Product,1987,Menengah
7,None,FEMALE,2015-07-20,10:43 AM,45906,11.598,None,Finance,2015,Rendah
8,Angela,FEMALE,2005-11-22,6:29 AM,95570,18.523,True,Engineering,2005,Menengah
9,Frances,FEMALE,2002-08-08,6:51 AM,139852,7.524,True,Business Development,2002,Tinggi

In [ ]:
# mengecek hasil akhir tabel di sql

query = """
SELECT COUNT(*) AS total_data
FROM employees;
"""

result = pd.read_sql(query, engine)

display(result)

   total_data
0        1000

In [ ]:
# mengecek hasil akhir tabel di sql
query = """
SELECT
    first_name,
    salary,
    kategori_gaji,
    start_date,
    start_year
FROM employees
LIMIT 10;
"""

display(pd.read_sql(query, engine))

  first_name  salary kategori_gaji start_date  start_year
0    Douglas   97308      Menengah 1993-08-06        1993
1     Thomas   61933      Menengah 1996-03-31        1996
2      Maria  130590        Tinggi 1993-04-23        1993
3      Jerry  138705        Tinggi 2005-03-04        2005
4      Larry  101004        Tinggi 1998-01-24        1998
5     Dennis  115163        Tinggi 1987-04-18        1987
6       Ruby   65476      Menengah 1987-08-17        1987
7       None   45906        Rendah 2015-07-20        2015
8     Angela   95570      Menengah 2005-11-22        2005
9    Frances  139852        Tinggi 2002-08-08        2002

In [ ]:
# mengecek hasil akhir tabel di sql

query = """
SELECT
    kategori_gaji,
    COUNT(*) AS jumlah_employee,
    ROUND(AVG(salary), 2) AS rata_rata_gaji
FROM employees
GROUP BY kategori_gaji
ORDER BY rata_rata_gaji DESC;
"""

result = pd.read_sql(query, engine)

display(result)

  kategori_gaji  jumlah_employee  rata_rata_gaji
0        Tinggi              409       124283.93
1      Menengah              445        75562.33
2        Rendah              146        42498.74

In [ ]:
# mengecek hasil akhir tabel di sql

query = """
SELECT
    team,
    COUNT(*) AS jumlah_employee,
    ROUND(AVG(salary), 2) AS rata_rata_gaji
FROM employees
GROUP BY team
ORDER BY jumlah_employee DESC;
"""

display(pd.read_sql(query, engine))

                    team  jumlah_employee  rata_rata_gaji
0        Client Services              106        88224.42
1                Finance              102        92219.48
2   Business Development              101        91866.32
3              Marketing               98        90435.59
4                Product               95        88665.51
5                  Sales               94        92173.44
6            Engineering               92        94269.20
7        Human Resources               91        90944.53
8           Distribution               90        88500.47
9                  Legal               88        89303.61
10                  None               43        90763.14